import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';

export default [
  // home/tmp holds scripts generated by in-place.ts; home/log is a runtime artifact.
  // Both are gitignored and excluded from tsconfig, so type-aware rules cannot see them.
  { ignores: ['home/tmp/**', 'home/log/**'] },

  js.configs.recommended,
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.es2021,
      },
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    rules: {
      semi: ['error', 'always', { omitLastInOneLineBlock: true }],
      'no-cond-assign': 'off',
      // Service loops are `while (true)` by design.
      'no-constant-condition': 'off',
      // ANSI escapes are how output is styled (lib/colors.ts), so the \x1b in the regexes that
      // strip and measure them is intentional.
      'no-control-regex': 'off',
      // `catch {}` is a deliberate swallow in a few places (mole.ts's password probing).
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tseslint.parser,
      sourceType: 'module',
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      '@typescript-eslint': tseslint.plugin,
    },
    rules: {
      // NS types are ambient globals.
      'no-undef': 'off',
      // The base rule counts parameters in a type signature as unused bindings, which produced
      // ~1050 false positives across the data-store and NS declaration files. tsc's noUnusedLocals
      // already catches the real cases, so this stays off rather than being swapped for the
      // typescript-eslint version.
      'no-unused-vars': 'off',
      // Make `by` function in lib/util.ts safer to use
      '@typescript-eslint/no-unsafe-unary-minus': 'error',
    },
  },
];
